POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzRmODM1Nzk2NzllOGRlODZmMjQxYyIsInVzZXJuYW1lIjoiTVNmdWNrQ3VycnkiLCJpYXQiOjE2NDc2MzkzNDUsImV4cCI6MTY0Nzg5ODU0NX0.ko2R8k0OWE-pXXylcnHQv75NQbV_IXfmmN9LJXtoOkA

{
    "content" : "im sorry steph :c",
    "important" : true
}