POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzRmODM1Nzk2NzllOGRlODZmMjQxYyIsInVzZXJuYW1lIjoiTVNmdWNrQ3VycnkiLCJpYXQiOjE2NDc4OTM3MTgsImV4cCI6MTY0ODE1MjkxOH0.PdpNOT9CwdcgjsFQazqPikmEKawUcjRnHLFrMCBV_Yc

{
    "content" : "probando"
}