POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name" : "Marcus Smart",
    "username" : "MSfuckCurry",
    "password" : "marcussmart10"
    
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "user" : "error falta username?",
    "password" : "melesionedenuevo123"
}