POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzI1MTE4YThhNjdhMTRiMjUzZTg1ZSIsInVzZXJuYW1lIjoiREcxMCIsImlhdCI6MTY0NzQ2OTg5N30.p_ZOktb1wJ37b6hnasHJ1TrXfFPzxU4iJOwiO-AcqfI

{
    "content" : "six? with user extractor",
    "important" : true
}